name: ai4s

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')"
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

  server:
    build: 
      context: ./server
    ports:
      - "5000:5000"
    container_name: ai4s_server_1
    environment:
      - CORS_ORIGIN=http://localhost:3000
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=24h
      - TOKEN_PREFIX=Bearer
      - MONGODB_URI=${MONGODB_URI}
      - PORT=5000
    networks:
      - app-network

  client:
    build: 
      context: ./client
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://ai4s_server_1:5000
      - REACT_APP_AUTH_HEADER=Authorization
      - REACT_APP_TOKEN_PREFIX=Bearer
    depends_on:
      - server
    networks:
      - app-network

  stilicognitivi:    # Nome semplificato del servizio
    build:
      context: ./engines
      dockerfile: stili_cognitivi/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=HS256
      - TOKEN_PREFIX=Bearer
      - FLASK_ENV=dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: