name: ai4s

services:

  server:
    build: 
      context: ./server
    ports:
      - "5000:5000"
    container_name: ai4s_server_1
    environment:
      - CORS_ORIGIN=http://localhost:3000
      # - NODE_ENV=development
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=24h
      - TOKEN_PREFIX=Bearer
      #- MONGODB_URI=mongodb+srv://RaikaSama:++Oo1903!!@ai4sDB.7leax.mongodb.net/?retryWrites=true&w=majority&appName=ai4sDB
      - PORT=5000
    
    env_file:
      - ./server/.env
    networks:
      - ai4s-network

  client:
    build: 
      context: ./client
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - REACT_APP_AUTH_HEADER=Authorization
      - REACT_APP_TOKEN_PREFIX=Bearer
    depends_on:
      - server
    networks:
      - ai4s-network

  stilicognitivi:    # Nome semplificato del servizio
    build:
      context: ./engines
      dockerfile: stili_cognitivi/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=HS256
      - TOKEN_PREFIX=Bearer
      - FLASK_ENV=dev
    networks:
      - ai4s-network

  # Definizione della rete alla fine del file
networks:
  ai4s-network:          # Cambiato il nome della rete
    driver: bridge


 
